### ISSUE TITLE
Project stage/step/phase seperation

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#116]
With using SMV in multiple real projects, it's clear that naturally there are some high level modules of each project. For example, the ETL step, there are always some very early stage work on the raw data for clean things up. There could be relatively well-defined separation between ETL process and further variable creation steps. However, it doesn't mean people (or code) on the variable creation steps do not need to know the implementation details of the ETL steps. It is also quite common that the fail of some business check on the output end actually lead to changes on the ETL step. 

Consider a 3 month project. It is quite common that 70% of ETL work is on the 1st month, and those 70% of ETL code could be updated on small issues in the rest 2 month with changing frequency as once a week. As a contrast, a typical module within a development process will be modified daily. To recognized the relative stability of the ETL outputs, we need to have a way to organize them within the SmvApp/SmvDataSet framework. Also ETL is just one of the "high level modules", For one project, typically there are 3-5 of those "high level modules".

I will call the "high level modules" the "steps" in this document. 

## Requirement
* Still need a single entry point to a project. Since we always need to have the full picture for end-to-end tracing and data debugging. A single project picture is a must-have
* Need a better name than "steps"
* Be able to label SmvModule's as "output smvModule" of a given step
* Downstream steps should be able to specify a version of the output SmvModule from the upper stream step. For example, Step2 and Step3 both depend on SmvModule1, which is an output module from Step1, at sometime in the project, Step2 requires Step1 to make changes on SmvModule1, so the version of that persisted file changed from V1 to V2. However Step3 is still working on some other thing and want to keep using V1 for 2 more days. Step3 should be able to do so
* Data flow chart need to group the steps and highlight to output modules

**Comment by AliTajeldin** [comment]
conceptually, this can be thought of as creating a version "snapshot" of the output files at a certain point in time.  This could either be implemented by versioning the "step" output directories or creating a snapshot by recording what the actual current version of each output file at a given period of time (similar to how RCS/CVS works).

**Comment by AliTajeldin** [comment]
There is slight problem with the above proposal.  The User will have to specify the actual version number of the file when using `SmvModuleOutputFile`.  This is rather inconvenient. After discussion with the team, the following proposal was decided upon:

The module output will only be output to the stage hierarchy described above if the "--publish-output" command line is specified.  The module output file that is published to the stage hierarchy will *NOT* have the file version so then the user does not have to specify the file version when using `SmvModuleOutputFile`

So the workflow is if a user wants to pin a dependency on a specific stage version, they run stage with the "--publish-output" flag and bump the configured stage version.

One additional proposal is to use symbolic name for the stage version instead of a number so that the snapped version will have a meaningful name.  The implementation should just assume the stage version is a string and it should be a matter of project policy whether it should be numeric or not.

**Comment by AliTajeldin** [comment]
closing this ticket as it will be resolved by issue #150 once it is implemented.
