### ISSUE TITLE
Create design doc for Simplify flow of DQM validation and SmvDataSet.computeDataFrame

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1249]
The control flow and order of operations in `computeDataFrame` gets pretty confusing due to details of when and whether to compute metadata, force an action to compute DQM results, etc. It's a bit tangled and could use a refactor.

**Comment by ninjapapa** [comment]
Since we removed DQM policy dependency to the result DF of the module, we can remove the "force-action" logic, instead, delay the policy validation to later actions.

**Comment by ninjapapa** [comment]
# High Level Behavior Design

* Metadata will only be calculated and persisted if the DS is NOT Ephemeral
* Make DQM validation part of Metadata calculation. However upper stream non-validated DQM state of ephemeral DS' will also be validated and result persisted in current DS metadata

@laneb @AliTajeldin 
Please review.

**Comment by AliTajeldin** [comment]
As per discussion with @ninjapapa we will "run" the ephemeral DQM rules on a module by module basis, even for ephemeral modules.  That is, if A -> B -> C and B is ephemeral, when A is "run", it will need to evaluate B and that will run the rules for B and the result of B DQM is persisted in B metadata.  If another module also depends on B, it will use the persisted B metadata rather than recompute it.

**Comment by laneb** [comment]
@AliTajeldin Does that differ from what we have today, other than in how the DQM result is persisted?

**Comment by AliTajeldin** [comment]
same.  We just no longer need the force flag.

**Comment by ninjapapa** [comment]
With removing the force run, current module's rdd calculation will not be able to trigger its DQM's policy check. So need to maintain a queue on App level to keep tracking the calculated ephemeral modules which have not been policy checked, and check the queue when a persisted module get calculated.

**Comment by ninjapapa** [comment]
For this issue, yes. No DQM policy checks if all modules are ephemeral. However, we should re-define persist of a output module (not current SmvOutput, but dedicated output module) as write to output DB or channels, which should never be ephemeral.

**Comment by jacobdr** [comment]
I think this would have broken our last client use case, so maybe we should discuss in person.
In that case we wanted to re-run ephemeral inputs hourly to detect early DQM issues, but defer full graph execution for the previous day to during a slow hour on the cluster (usually overnight).
Maybe since the runtime params were different for each invocation this would cache bust, but not sure how that plays in to the refactor.

**Comment by ninjapapa** [comment]
@jacobdr we will create a method to force a DQM check. For above use case, the hourly re-run can explicitly call that method. Will this mechanism addresses the need?

**Comment by ninjapapa** [comment]
# Design

## New Behavior

* Only one metadata file (no more `.valid`, `.edd`)
* Metadata calculation (including dqm policy check) performed at the nearest downstream persisting process - if current module need persist, calculate, else delay to later module's persist to calculate 
* Once a module's metadata is calculated and the `.meta` file persisted, read from it, instead of re-calculate
* EDD will be a user-defined metadata
* Ephemeral module will skip user-defined metadata calculation
* New shell command and command line parameter will be added to force a metadata calculation for specific modules

## Implementation 
The logic in `computeDataFrame` will look like
```scala
if(quickRun) {
    doRun(...)
} else if(isEphemeral) {
    registerModuleForDelayMeta(...)
    dqmValidator.attachTasks(doRun(...))
} else {
    readPersistedFile() match {
        case Success(df) =>
            df
        case _ => {
            SmvLock.withLock(lockfilePath()) {
            readPersistedFile() match {
                case Success(df) =>
                    df
                case _ => {
                    val df = dqmValidator.attachTasks(doRun(...))
                    runPersistAction(df)
                }
            }
        }
    }
}
```

Where the `runPersistAction` looks like:
```scala
def runPersistAction(df) {
    persist(df)
    createSystemMeta()
    val dfReadBack = readPersistedFile()
    createUserMeta(dfReadBack)
    persistMeta()
    ancestors.foreach{m =>
        if(m is registered){
            if (no persisted meta) {
                m.createSystemMeta()
                m.persistMeta()
            }
            unregisterModuleForDelayMeta(m)
        }
    }
    dfReadBack
}
```

**Comment by ninjapapa** [comment]
@laneb @AliTajeldin Please review.

**Comment by ninjapapa** [comment]
Delay system meta is because DQM validation is part of it.

**Comment by laneb** [comment]
Ok I reread the conversation above and I think I've got this now.  When a non-ephemeral module runs, all upstream ephemeral modules' DQM state is calculated via the accumulator approach we have today. `createSystemMetadata` includes applying `DQMPolicies` to the `DQMState` which is guaranteed to have been calculated already.

**Comment by laneb** [comment]
This is cool!

**Comment by ninjapapa** [comment]
Exactly.

**Comment by laneb** [comment]
Does forcing a module to generate its metadata force upstream modules' metadata?

**Comment by AliTajeldin** [comment]
I think we need to keep the data persistence separate from the metadata persistence.  User may have made the module ephemeral due to large size of output and not due to computation complexity.

**Comment by ninjapapa** [comment]
@AliTajeldin make sense. Will update the pseudo code.

**Comment by ninjapapa** [comment]
@laneb @AliTajeldin Updated with "forceMetaCreation" flag.

**Comment by ninjapapa** [comment]
To remove confusion, should rename the flag to `forceEphemeralMetaCreation`.

`forceEphemeralMetaCreation` will be passed in as a parameter of `runModule` with default `False`.

**Comment by AliTajeldin** [comment]
@ninjapapa I think we need a quick whiteboard session on this.

**Comment by ninjapapa** [comment]
As discussed with @AliTajeldin , ideally we will allow user to attach user defined metadata method to an Ephemeral module. Although in user doc or other places we should let user aware that operation could be expensive and contradictory to Ephemeral flag. 

Also we want to change the "quickRun" flag's behavior. Instead of alway just return the df itself, a `rdd` with `quickRun` flag should be smart enough to use persisted data if possible, while avoiding persist any new data. 

Given above complexity, we tern this issue to a Type 3 issue. And change the scope of this issue to just create the design document.
