### ISSUE TITLE
Fix test_smvTimestampToStr

### ISSUE THREAD

**Issue by cloudysail** [TresAmigosSD/SMV#1280]
The test looks like this
```
    def test_smvTimestampToStr(self):
        df = self.createDF("ts:Timestamp[yyyyMMdd'T'HHmmssZ];tz:String", "20180428T025800+1000,+0000;,America/Los_Angeles;20180428T025800+1000,Australia/Sydney")
        r1 = df.select(col("ts").smvTimestampToStr("+10:00","yyyyMMdd:HHmmssz").alias("localDT"))
        r2 = df.select(col("ts").smvTimestampToStr(col("tz"),"yyyy-MM-dd HH:mm:ssz").alias("localDT2"))

        e1 = self.createDF("localDT: String", "20180428:025800+10:00;;20180428:025800+10:00")
        e2 = self.createDF("localDT2: String", "2018-04-27 16:58:00+00:00;;2018-04-28 02:58:00+10:00")

        self.should_be_same(e1, r1)
        self.should_be_same(e2, r2)
```
We should use `Z`(RFC 822 time zone) rather than `z`(General time zone) according to the [SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html)

**Comment by laneb** [comment]
Was this test passing before? The build on master is green.

**Comment by laneb** [comment]
What is this test intended to verify? Is it not a problem that the behavior is inconsistent?

**Comment by laneb** [comment]
Having another read of the `SimpleDateFormat` documentation, it looks like RFC-822 is the only format which has only a single valid way to represent a given offset. (E.g. UTC and +00:00 are equally valid representations of the UTC timezone in the General Time Zone format). Seems reasonable to use RFC-822 then and let the representation of less consistent formats be a platform issue since `SimpleDateFormat` can still parse the timestamps regardless.

**Comment by cloudysail** [comment]
Right, not sure what exactly platform difference will make the result for `z` different, but `Z` would be definitely safe.
