### ISSUE TITLE
run_app -m should accept base module name

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#155]
We now require the user to supply the full module FQN to the "-m" command line option .  So user must type:
```bash
$ ./tools/run_app.sh -m com.mycompany.foo.bar.abc
```
to run the "abc" module.  If "abc" is a unique module name in the code, the user should be able to just run:
```bash
$ ./tools/run_app.sh -m abc
```

Makes it easier to run when one copy-n-paste from editor to run the current working module :-)

**Comment by AliTajeldin** [comment]
Need to do the same for "-s" flag for stages once #201 is implemented.

**Comment by Kai-Chen** [comment]
All packages specified in stage, as well as their parents, are searched in order to resolve a singleton companion object (static module) with the base name.  If there are more than 1 module found with the same base name, a RuntimeException will be thrown (see accompanying tests).

A module base name can also contain any number of containing packages.  For example, the module org.tresamigos.smv.test1.pkg1.TestModule can be specified, after the '-m' switch, as any of 'TestModule', 'pkg1.TestModule', 'test1.pkg1.TestModule', etc.
