### ISSUE TITLE
Need a get_content_list method for connections

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1576]
Client code:
```python
my_conn = smvApp.get_connection_by_name('my_hdfs')
csv_files = my_conn.get_content_list(pattern=r".*\.csv", ignore_case=True)
```

**Comment by ninjapapa** [comment]
Since `get_content_list` have to use spark context, if might be better to make it a `SmvApp` method.

**Comment by AliTajeldin** [comment]
* I think the method should probably stay on the `conn` instance.  From user experience, they are acting on a connection.
* Because other connections will not have a concept of pattern and case, we should probably define the base `get_content_list` as a function with keyword args `**kw` so that other connection types can define other filter params.

**Comment by ninjapapa** [comment]
* Agree
* Why hive connection does not need pattern? Could also have, right?

**Comment by ninjapapa** [comment]
Or maybe pattern should be an attribute of that connection....

**Comment by AliTajeldin** [comment]
probably should have said "might not have" instead of "will not have".   Hive will have pattern but other future connection types may not have that concept.

**Comment by AliTajeldin** [comment]
pattern should probably stay with the `get_content_list`.  cleaner than splitting the content filter criterion between two places (in constructor and in getting content list).
Also, we may want to use pattern to filter out large connection lists as user type in (rather than our usual case of getting all items and filtering the in-memory list)

**Comment by ninjapapa** [comment]
Will get everything without the pattern match.

**Comment by ninjapapa** [comment]
Fo JDBC, the ways to get a list of tables are different for different DBs.

* [MySql](https://dev.mysql.com/doc/refman/8.0/en/tables-table.html)
* [mssql](https://www.mssqltips.com/sqlservertutorial/196/informationschematables/)
* [derby](https://db.apache.org/derby/docs/10.5/ref/rrefsistabs24269.html)
* [postgresql](https://stackoverflow.com/questions/2276644/list-all-tables-in-postgresql-information-schema)
* [Oracle](https://stackoverflow.com/questions/205736/get-list-of-all-tables-in-oracle)
