### ISSUE TITLE
Provide method to unpivot (reshape) multiple sets of columns

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#243]
## Motivation

Some of the raw data we've encountered flattens a matrix into a row like below

Id | A_1 | A_2 | ... | A_11 | B_1 |  ... | B_11 | ... | Z_1 |  ... | Z_11 |
---|---|---|---|---|---|---|---|---|---|---|---|

and we would like to be able to transform it back into its un-pivoted matrix form, such as this

Id | Index | A | B | ... | Z |
---|---|---|---|---|---|

ideally with a simple method in SmvDFHelper like
```scala
  def smvUnpivotN(colNames: Seq[Seq[String]]): DataFrame = ???
```

## Current Implementation
SMV currently provides a method `smvUnpivot`, in SmvDFHelper, that performs the following data frame transformation

 Id | X | Y | Z |     
 ---|---|---|---|     
| 1  | A | B | C |     
| 2  | D | E | F | 
| 3  | G | H | I |     
                       
==>

 Id | column | value |
---|------|-----|
|  1 |   X    |   A   |
|  1 |   Y    |   B   |
|  1 |   Z    |   C   |
| ... | ...   |   ...  |
|  3 |   Z    |   I   |

This is sufficient, after being applied multiple times, once for each column set, to produce the desired result with a joinByKey.  However, there is also room here to implement a single-pass method, especially if more and more data are found to be in this format, and similar transformation would be desirable for further analysis.

**Comment by ninjapapa** [comment]
Current `smvUnpivot` method has the `column` and `value` fields hard-coded. If we consider a generic approach the single column unpivot should be just a special case of the multiple column case. 

For the multiple column unpivot example, instead of assuming the structure of the column names as 
`prefix_index`, we should allow a way to specify the matrix structure of the columns
```scala
Map("A_1" -> ("A", 1), "A_2" -> ("A", 2), ... "A_11"->("A", 11), ... "Z_11"-> ("Z", 11))
```

In the single column unpivot case the map will be 
```scala
Map("X" -> ("value", "X"), "Y" -> ("value", "Y"), "Z" -> ("value", "Z"))
```
The only change there will be that the name of "column" is changed to "Index". 

This approach may not be very convenience if we use the map as the parameter of the `smvUnpivot` method. To make it's more user friendly, we can create a case class as the following
```scala
case class UnpivotParam(colGroupNames: Seq[String], colIndexNames: Seq[String], colNameCreater: (String, String) => String)
```
where `colGroupNames` are `A`, `B`, ... `Z`, and `colIndexNames` are `1`, `2`, ..., `11`. The `colNameCreater` is `(grp:String, ind:String) => grp + "_" + ind`.

For the single column example, `colGroupNames` is `Seq("value")`, `colIndexNames` is `Seq("X", "Y", "Z")`, and `colNameCreater` is `(grp:String, ind:String) => ind`.

With above approach, the client code will look like
```scala
df.smvUnpivot(UnpivotParam(Seq("A", "B", ..., "Z"), Seq(1, ..., 11), (g, i) => g + "_" + i))
```

**Comment by ninjapapa** [comment]
The case class may not be necessary. Could be just multiple parameters.

Also since `smvPivot` has the following signature
```scala
df.smvPivot(pivotCols: Seq[String]*)(valueCols: String*)(baseOutput: String*)
```
We may want to make `smvPivot` and `smvUnpivot` more symmetric.

The unpivot use case only have a single "index" dimension, and based on our experience supporting multiple index dimension for unpivot may not be necessary. Using the naming convention of `smvPivot`, the "colIndexNames" are "baseOutput", and the "colGroupNames" are "valueCols", and we hard coded "pivotCols" as "Index", which has only one dimension. 

The interface could be
```scala
smvUnpivotN(colToKeep: String*)(colToInedxValues: String*)(colNameCreator: (String, String) => String)
```
We have to separate `smvUnpivotN` from `smvUnpivot`, since otherwise the current single column unpivot interface need to be changed.

Another option is 
```scala
smvUnpivot(colToKeep: Seq[String], colToIndexValue: Seq[String], colNameCreator: (String, String) => String)
```
In this case we don't need to change the original single column unpivot.

**Comment by Kai-Chen** [comment]
Would a mirror-image signature work better?

```scala
  def smvUnpivot(valueCols: Seq[String],
                 colNameFn: String => (String, String),
                 indexColName: Option[String] = Some("Index")): DataFrame
```

* `valueCols` is the names of the columns to be unpivoted, e.g. `Seq("A_1", "A_2", ..., "Z_11")`
* `colNameFn` defines how to split each name (of the column) into a tuple
  * first part of the tuple is the column name after it is unpivoted, i.e. the category
  * second part of the tuple is the index value
  * e.g. `"A_1" => ("A", "1")`
* `indexColName` is an optional parameter that names the column containing the index value after reshaping.  If it's None, the index value column would not be added.

The current unpivot operation would then be equivalent to calling the new method with
```scala
smvUnpivot(valueCols, colNameFn = s => (s, s), indexColName = None)
```

**Comment by ninjapapa** [comment]
I like this interface!

Should the current single column `smvUnpivot` be the following?
```scala
smvUnpivot(valueCols, colNameFn = s => ("value", s), indexColName = Some("column"))
```

**Comment by Kai-Chen** [comment]
That's right!  My earlier attempt was complete gibberish :) and would not have done any unpivoting.

So the default colNameFn and indexColName parameter values could be provided such that when the user gives only a sequence of column names to unpivot, the method would have exactly the same behavior as before.  If we want to keep the same varargs signature, we could move the valueCols to the last position, while using the name colTransFn for the first parameter (transpose, transform, etc)
```scala
 def smvUnpivot(colTransFn: String => (String, String) = s => ("value", s)
                indexColName: Option[String] = Some("column"),
                valueCols: String*): DataFrame
```

**Comment by ninjapapa** [comment]
Still prefer this
```scala
  def smvUnpivot(valueCols: Seq[String],
                 colNameFn: String => (String, String),
                 indexColName: Option[String] = Some("Index")): DataFrame
```
Just need to add another  
```scala
  def smvUnpivot(valueCols: String*): DataFrame = smvUnpivot(valueCols, s => ("value", s), Some("column"))
```

**Comment by Kai-Chen** [comment]
Implemented using the same strategy as the current single-column unpivot, using spark's explode() API to generate multiple rows, and expanding it to work with multiple columns.
