### ISSUE TITLE
Implement aggregation options for GroupedData's smvPivotAgg

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#283]
Currently, we have smvPivotSum, smvPivotCoalesce. These functionalities can be under the same umbrella: smvPivotAgg. Multiple aggregation options can be provided, such as:
- for numeric valueCols, there can be: sum, mean, max, min, and etc...
- for string Cols, there can be: coalesce, append, takeLast, and etc...

The interface may look like this:
def smvPivotAgg(pivotCols: Seq[String]_)(valueCols: String_)(baseOutput: String_)(aggOption: String_)

**Comment by Kai-Chen** [comment]
See also #279

**Comment by laneb** [comment]
Is something like this still needed?

**Comment by AliTajeldin** [comment]
@XiaosenChen , @Kai-Chen

**Comment by XiaosenChen** [comment]
I think so, unless spark 2+ provides good options and we are migrating soon.
@ninjiapapa

**Comment by Kai-Chen** [comment]
I think a good deal of this can be achieved by using the currently available API.

### Example 1
#### Starting Dataframe
Gven the following data frame
```output
scala> df1.show()
+---+-----+-------+-----+
| id|month|product|count|
+---+-----+-------+-----+
|  1| 5_14|      A|  100|
|  1| 6_14|      B|  200|
|  1| 5_14|      B|  300|
+---+-----+-------+-----+
```
#### Using SmvPivotSum
```output
// sum total sales by month and product
scala> df1.smvGroupBy("id").smvPivotSum(Seq("month", "product"))("count")().show()
+---+------------+------------+------------+
| id|count_5_14_A|count_5_14_B|count_6_14_B|
+---+------------+------------+------------+
|  1|         100|         300|         200|
+---+------------+------------+------------+

// sum total sales by product
scala> df1.smvGroupBy("id").smvPivotSum(Seq("product"))("count")().show()
+---+-------+-------+
| id|count_A|count_B|
+---+-------+-------+
|  1|    100|    500|
+---+-------+-------+
```
#### Using SmvPivot and Spark's agg method
```output
// sum total sales by month and product
scala> df1.smvGroupBy("id").smvPivot(Seq("month", "product"))("count")().agg(
     | "count_5_14_A" -> "sum", "count_5_14_B" -> "sum", "count_6_14_B" -> "sum").show()
+---+-----------------+-----------------+-----------------+
| id|sum(count_5_14_A)|sum(count_5_14_B)|sum(count_6_14_B)|
+---+-----------------+-----------------+-----------------+
|  1|              100|              300|              200|
+---+-----------------+-----------------+-----------------+

// sum total sales by product
scala> df1.smvGroupBy("id").smvPivot(Seq("product"))("count")().agg(
     | "count_A"->"sum", "count_B"->"sum").show()
+---+------------+------------+
| id|sum(count_A)|sum(count_B)|
+---+------------+------------+
|  1|         100|         500|
+---+------------+------------+

```

**Comment by Kai-Chen** [comment]
The syntax is a bit awkward using `smvPivot` together with Spark's `agg`, because you have to pass in the function name as a String and also because you have to manually construct the column names after the pivot operation.
But this should be able to handle most, if not all, the aggregate functions that one may need.

Of note is that `null`-handling can be tricky and may yield different results using the two methods mentioned above.

### Example 2

#### Starting Dataframe
```output
scala> df3.show()
+----+---+---+
|   k|  p|  v|
+----+---+---+
|   1|  A|  3|
|   1|  B|  4|
|   2|  A|  5|
|null|  A|  3|
+----+---+---+
```

#### Using SmvPivotSum
```output
scala> df3.smvGroupBy("p").smvPivotSum(Seq("k"))("v")("1", "2").show()
+---+---+---+
|  p|v_1|v_2|
+---+---+---+
|  B|  4|  0|
|  A|  3|  5|
+---+---+---+

scala> df3.smvGroupBy("p").smvPivotSum(Seq("k"))("v")().show()
+---+---+---+------+
|  p|v_1|v_2|v_null|
+---+---+---+------+
|  B|  4|  0|     0|
|  A|  3|  5|     3|
+---+---+---+------+
```

#### Using SmvPivot and agg
```output
scala> df3.smvGroupBy("p").smvPivot(Seq("k"))("v")("1", "2").agg(
     | "v_1" -> "sum", "v_2" -> "sum").show()
+---+--------+--------+
|  p|sum(v_1)|sum(v_2)|
+---+--------+--------+
|  B|       4|    null|
|  A|       3|       5|
+---+--------+--------+


scala> df3.smvGroupBy("p").smvPivot(Seq("k"))("v")().agg(
     | "v_1"->"sum", "v_2"->"sum", "v_null"->"sum").show()
+---+--------+--------+-----------+
|  p|sum(v_1)|sum(v_2)|sum(v_null)|
+---+--------+--------+-----------+
|  B|       4|    null|       null|
|  A|       3|       5|          3|
+---+--------+--------+-----------+
```

**Comment by Kai-Chen** [comment]
In addition, since Spark 1.6, there is the `pivot` method on `GroupedData`, which is renamed `RelationalGroupedDataset` in Spark 2.x.
This method yields similar results.

To use that on multiple columns, one would need to first use `smvStrCat` to concatenate the columns together, and there, again, `null` values can cause problems.

Maybe we can try using these plumbing methods to see if they are sufficient?

Alternatively, to provide a consistent handling of `null`s, we can provide a more porcelain API that handles the naming of pivoted columns which, though internal to SmvPivot, is still exposed to the user in the output.

@ninjapapa Please comment if there's anything wrong or left out in the above.

**Comment by ninjapapa** [comment]
Here is what I think we should do:

* [ ] add docstr document for `smvPivotSum` to emphasis that we coalesced the sum result to zero for nulls
* [ ] add `smvPivot` followed by `agg` example in `smvPivot`'s docstr. Please note that the return of `smvPivot` on Python side is a DataFrame, so the example need to have `groupBy(.).agg(.)` instead of just `agg`. Also please use the following style for agg function:
```python
df.smvGroupBy('id').smvPivot([['k']], ['v'], []).groupBy('id').agg(sum('v_1'), sum('v_2'))
```

* [ ] Given that Spark's `agg` function can take aggregate function as a string, there is a potential implementation of this `smvPivotAgg` method. Here is the potential client code:
```python
df.smvGroupBy('id').smvPivotAgg("sum", [['k']], ['v'], [])
```

Point 2 and point 3 are both needed since they can cover different use cases. For example point 2 method can have one `sum` and one `avg`.

**Comment by XiaosenChen** [comment]
I think this may not worth the effort.
spark 1.6 + seem to handle pivot very well and its behavior is quite standard.
Can we hold off on this for now, I can test a more comprehensive list of all use cases next week. We can decide whether to move forward then?
@ninjapapa is there a reason we want to encourage the use of smvGroupBy for aggregate when depending on later versions of Spark(say 2.0)? such as for performance consideration?

**Comment by XiaosenChen** [comment]
Spark 1.6+ pivot behavior reviewed. I think it is clean and sufficient.
Since we already have 1.6+ and 2.1+ releases, this issue will close.
