### ISSUE TITLE
Nee a method to differentiate empty string VS null 

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#304]
When persis a smvDataSet, empty string are persisted as empty string, however, when read back, empty string will be read as null, therefore create inconsistency.

**Comment by ninjapapa** [comment]
Although we are joking on using string "null" to represent null value of a string field, we have actually no significantly better ways than that if we do want to persist data as CSV files. 

There could be 2 options: 
* Move to other persisting format which can handle schema with nulls
* Define a special string to represent null string value and create a CsvAttribute to specify that string

In the longer term anyhow we will likely to persist in other format. However since that move may have some risks, we may not want to do it without prepared. So in the short term we will take the second approach.

**Comment by ninjapapa** [comment]
Actually the special string to represent null string should be an attribute of the field, instead of a CsvAttribute. We could add it similarly as the format string in the schema file.

**Comment by ninjapapa** [comment]
Still need document in user doc.

@Kai-Chen 
We are smarter then the people who use "null" to represent null string, since we use "_SmvStrNull_"! 
:-)

**Comment by ninjapapa** [comment]
done

**Comment by Kai-Chen** [comment]
Death to Null! :D
