### ISSUE TITLE
smvDay70/smvMonth70 test failed

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#315]
- test smvDay70/smvMonth70 *** FAILED ***
  "1539[8]" did not equal "1539[9]" because array element 15398 not equal 15399 (SparkTestUtil.scala:133)

**Comment by ninjapapa** [comment]
Really interesting. It must be related to some wrong handling of time zones.

**Comment by XiaosenChen** [comment]
i thought so, cause it is only 1 day difference.

**Comment by ninjapapa** [comment]
I found the issue, but need to think before taking actions...
The reason is that we use java SimpleFormat to read a string and convert to Timestamp internally. However, by default that method assume the string is in Local timezone (machine system tz). When we try to convert it to day70, we specifically set the TZ to UTC. There are 2 ways to fix it:
* Load String from CSV as UTC (change the internal representation)
* Fix day70 to use local time instead of UTC

**Comment by ninjapapa** [comment]
Changing the internal representation is too risky. For now keep the internal representation as local timezone, fixed day70 to make it consistent with that.
