### ISSUE TITLE
Changing in string constant within a module will not cause crc changing

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#316]
Since the constant string is not stored in the class itself, changes within the string constant may not cause changes on the class byte code. We need to enhance the ASM CRC calculation by following the string reference to the string value and use the value as part of the CRC.

**Comment by ninjapapa** [comment]
It's actually a much bigger problem. Since when we tried to make CRC depend on the parents classes, we actually made the CRC ONLY depends on the parents. Sine typically a module is an Object, it has 2 classed in java, one with the same FQN as the object, one with the FQN with a '$" as the postfix. The FQN passed to ClassCRC is the one with "$", and the one without "$" is actually one of its parents. So we only calculated CRC based on the class without the "$", which actually has the "run" method as a static and has no real content of the real run method. 

Because of all those, any changes within the run method will not cause a CRC change!

**Comment by Kai-Chen** [comment]
Nice find!.  As I was taking a closer look and found that the TraceClassVisitor does print out the String constant in the trace, so any change in the constant would result in a change in the checksum.  The bug was indeed in the class hierarchy walk, which was done a bit too quick :P I will add some more tests soon!
