### ISSUE TITLE
Need to add docs for new label functions

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#318]
Need to update the user doc to add docs for the new label functions (SmvGetLabel, RemoveLabel, etc) and how to use them with projections.

**Comment by ninjapapa** [comment]
Smv support 2 types of meta data in schema: SmvLabel and SmvDesc. Need to uniform the interface of those 2 and summarize in a user doc. 

## Current SmvDesc

`SmvDesc` is used carry column level description. Current interface:
```scala
df.select($"field1" as "f1" withDesc "this is the first field")
df.selectWithReplace($"field1" with Desc "this is the first field")
```
Each field (column) can only have 1 description. Any new one replace the old one. Also since `SmvDesc` was implemented first, there were no other column level metadata supported, any new description assignment will remove original column level metadata.

## Current SmvLabel

`SmvLabel` is used to "tag" the columns. Each column can have a Set of labels. A group of DF level methods were created to support label assignment and querying. 

```scala
val df1 = df.smvLabel("field1")("A", "B")                    //Assign "A", "B" to column "field1"
val df2 = df1.smvRemoveLabel("field1")("A")           //Remove label "A" from column "field1"
val df3 = df2.smvWithLabel("B")                              //Select columns with label "B"
```

Operation on `SmvLabel` will not impact other existing metadata (including `SmvDesc`).

## Improvements 

* Create DF level SmvDesc interface 
* DF level SmvDesc operation should not impact existing meta data 
* Rename `smvWithLabel` to `selectByLabel` to describe the function better
* Allow `smvLabel` to add label to all the columns of a DF

**Comment by AliTajeldin** [comment]
Done
