### ISSUE TITLE
SmvCsvFile() read files with record separator in one column

### ISSUE THREAD

**Issue by jackyact** [TresAmigosSD/SMV#320]
While reading raw csv files by SmvCsvFile(), it leads to errors if one or multi columns contain record separator. An example is attached. The full_address sometimes shown as it appears in the envelope.

[hc_example.zip](https://github.com/TresAmigosSD/SMV/files/310016/hc_example.zip)

**Comment by ninjapapa** [comment]
Here are 2 records in the example
```
10091,GROVE HILL MEMORIAL HOSPITAL,295 JACKSON HWY S,GROVE HILL,AL,36451,CLARKE,2512753191,Acute Care Hospitals,Governm
GROVE HILL, AL 36451
"
010097,ELMORE COMMUNITY HOSPITAL,500 HOSPITAL DRIVE,WETUMPKA,AL,36092,ELMORE,3345674311,Acute Care Hospitals,Government
WETUMPKA, AL 36092
"
```

The problem here is that before parsing the columns there is no way to split the file to records since sometimes the line breakers are record separators and sometimes is a value in a field. Although the CsvParser Java library we use can handle this case correctly, we load the data in using Spark's `SparkContext.testFile` which split data to partitions by line breakers, therefore we can't assume a record is actually within the same partition. If the data is small enough(smaller than HDFS file block size), we can specify the minimal partition parameter of `textFile` to one and then parse it. Otherwise we may need to store the rejected record per partition and then combine them to one and send to CsvParser.

**Comment by Kai-Chen** [comment]
Since SparkContext.textFile splits input using linebreaks, the one-line-per-input-record format essentially is an implicit part of the Spark API.  A corresponding work-around, then, would be to use a tool to pre-process input files to join together quoted multi-line records.

For example, a perl script might look like this:

```perl
#!/usr/bin/env perl

use strict;

my $acc = "";
my $qc = 0;

while (<>) {
		chomp;
		$qc = $qc + ($_ =~ tr/"//);
		$acc = "$acc$_";
		if ($qc % 2 == 0) {
				print "$acc\n";
				$qc = 0;
				$acc = "";
		}
}

if ($acc) {
		print "$acc\n";
}
```

**Comment by ninjapapa** [comment]
This one and some other things like the Hive table last update time issue should be part of a FAQ document, since they are not solvable within the SMV scope.
