### ISSUE TITLE
Port commonly used DF helper methods to Python

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#379]
- [x] smvDedupByKey
- [x] smvDedupByKeyWithOrder
- [x] smvExportCsv
- [x] smvJoinByKey
- [x] smvJoinMutipleByKey
- [x] peek(. , .)
- [x] smvRenameField
- [x] smvSelectMinus
- [x] smvHashSample
- [x] smvUnion
- [x] smvExpandStruct

In general any method which returns a DF should be easily ported to Python

**Comment by Kai-Chen** [comment]
@ninjapapa 
I went over the mechanics with George, and one thing that came up is the question whether we should keep the method names exactly the same or add the `smv` namespace for Python in all the method.  In other words, should `dedupByKey` stay as `dedupByKey` or become `smvDedupByKey` in the Python API?

I can see arguments for both, and would like to see what you and @AliTajeldin think.

**Comment by Kai-Chen** [comment]
Discussed naming convention with Ali.  He is of the opinion that we should start prefixing `smv` to all the enhancer methods exposed to the Python API.  One reason is to avoid future collision in Python's namespace.  Another reason is so that we won't have to do the work both for Python and Scala later.  And a third reason is that, since we're starting with a clean slate, this is a good opportunity to unify around a good naming convention.

A parallel effort on the Scala side should be that we also provide the same method with the `smv` prefix, where there is none, and deprecate the existing method.  For example, we should add `smvSelectPlus` to DFHelper, and deprecate the current `selectPlus`.

**Comment by Kai-Chen** [comment]
### Note
- See `smvSelectMinus` for an example of how to solve overloading on the Scala side (`SmvPythonHelper`)
- See `smvHashSample` for an example of how to solve overloading on the Python side (`smv.py`)
- See `src/test/python/testEnhancer.py` for testing the glue code.  You only need to pick 1 from the possibly many tests in Scala, as all functionalities will be tested on the Scala side, and the python tests are just to make sure that you won't have any errors calling from Python.

**Comment by Khorkhe** [comment]
Scala unit tests make use of a "assertUnorderedSeqEqual" function.  Is there anything similar yet on the Python side?

**Comment by Kai-Chen** [comment]
Not yet.  But `should_be_same` method should work for most situations.  I will implement the set equals check when I'm done with module versioning and other items.
