### ISSUE TITLE
Second smv-pyshell can't start due to port in use

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#401]
When one try to start the second smv-pyshell, an error happens.

```
starting callback server on port 25334
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/python/pyspark/shell.py", line 79, in <module>
    execfile(_pythonstartup)
  File "/home/users/zhangb32/Tresamigos/SMV/tools/conf/smv_pyshell_init.py", line 46, in <module>
    app = SmvApp.init(['-m', 'None'], sc, sqlContext)
  File "/home/users/zhangb32/Tresamigos/SMV/python/smv.py", line 173, in init
    gw._start_callback_server(cbs_port)
  File "/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 867, in _start_callback_server
  File "/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/python/pyspark/streaming/context.py", line 68, in start
    raise Py4JNetworkError(msg)
py4j.protocol.Py4JNetworkError: An error occurred while trying to start the callback server: [Errno 98] Address already in use
```

**Comment by ninjapapa** [comment]
Before figuring out how to fix this in the right way, I need to put in a temporary work-around. Since user should be able to pass in a command line parameter when init a SmvApp, I will pass in a random port number in `smv_pyshell_init.py`.

**Comment by Kai-Chen** [comment]
Yes, this is a known issue, but only to myself I guess :)  The problem is that pyspark, which `smv-pyshell` invokes, does not accept additional application arguments.  The reason why `smv-pyrun`, on the other hand, does accept the `--cbs-port` option is because it invokes `smvapp.py`, which is a python script that starts SmvApp, which then initializes a SparkContext.  We get a chance to parse the command line from there.

One possibility is that we could add an `smv.cbsPort` configuration in `smv-app-conf.props`.  Another option, which could be implemented together with the previous one, is to look for the `SMV_CBS_PORT` environment variable in `smv_pyshell_init.py`.  This would probably be the first environment variable we accept.

**Comment by AliTajeldin** [comment]
I think there are two distinct cases here.
1. app/shell is being run in an open environment (no restrictions on which ports can be open).
2. A restricted environment where user must request ports to be opened ahead of time.

In the first case, rather than require a config parameter (which must be different per user, per simultaneous runs), bind to a random high number port.  Then use the traditional py4j channel to send the port number back to the scala side.  Not sure how complex this would be to implement.

In the second case, I prefer the use of "smv.cbsPort" configuration parameter which can be specified in the user config file (which one would only have to specify in the restricted environment).  We would then remove the use of the "--cbs-port" command line option all together as it is not consistent.
--
Ali

**Comment by ninjapapa** [comment]
Need to add the "random port" temporary fix to smv-pytest also.

**Comment by ninjapapa** [comment]
This issue is duplicate. Close this one, keep the new one.
