### ISSUE TITLE
SMV exception message need to indicate it's from SMV

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#418]
The following is the error message when resolving a module failed,
```
10:06:08 PERSISTING: hdfs:///applications/gidr/processing/stg/spark/esbriet/data/output/com.gene.gsonar.esbriet.layer5.P
er1_5277a0c9.csv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/zhangb32/Tresamigos/SMV/python/smvshell.py", line 20, in <lambda>
    ddf = lambda fqn: SmvApp.runDynamicModule(fqn)
  File "/home/users/zhangb32/Tresamigos/SMV/python/smv.py", line 198, in runDynamicModule
    return DataFrame(self.app.runDynamicModule(fqn, self.repo), self.sqlContext)
  File "/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py",
 line 538, in __call__
  File "/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/python/pyspark/sql/utils.py", line 42, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1])
pyspark.sql.utils.IllegalArgumentException: unknown type: NullType
```

The real issue is that there is a column of the output DF of this module has `NullType` as DataType. The exception was actually raised by SMV when SmvSchema try to convert the value to a string and store to a CSV file (in SmvSchema.scala). 

To make this message more useful, we either need to print out the error stack from Scala side (which has file and line number), or the SMV error message itself should provide more info, at least to indicate the error was generated by SMV.

**Comment by Kai-Chen** [comment]
Pyspark intercepts Exceptions in the `spark.sql` package and also `java.lang.IllegalArgumentException` to present a shortened error message without Java stack trace.  Given this, we should never throw `java.lang.IllegalArgumentException` from the Scala code so that, in an error situation, the stack trace wouldn't squelched by pyspark and will show up on the Python side.

We should also introduce an `SmvRuntimeException` that extends from `RuntimeException`.  This should be the top-level Exception class in the SMV Exception Hierarchy.

Subtypes of `SmvRuntimeException` can be added for
- Rejection of input data from DQM policy
- Unsupported data type for polymorphic functions or custom operations
- Various precondition checks

and others.

**Comment by ninjapapa** [comment]
done
