### ISSUE TITLE
Cannot access notebook with local browser when running smv-jupyter docker

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#430]
It seems after building the docker smv-jupyter, and then running the command `docker run -it -p 8888:8888 -v /path/to/proj:/proj smv-jupyter`, the notebooks cannot be viewed in browser with http://localhost:8888.

**Comment by ninjapapa** [comment]
Here is a philosophical question:
***Should we even provide the entry point other than bash?***

I tried the 3 images:
* smv-core
* smv
* smv-jupyter

The only one run without any issue is the `smv-core`. 
* `smv` image error out after I upgraded my docker on my Mac OS. I suspect `pip` command in the Dockerfile was not installed before use, so the host's `pip` was tried, and failed. 
* Tried `smv-jupyter` on a Linux machine. It built successfully, but when run, it said no fat jar found. The reason is that our entry point script was try to start the note book

Anyhow the `smv` image issue should be handled separately. My main point here is that
* The docker image should make project developers (using SMV to develop data applications) live easier. In other words, users should not need to learn too much of how docker works, it should just work
* Users workflow is ad hoc anyhow, so we can't consider the dockers are apps, instead, they should be working environment
* Atom and/or IDEs should not be part of the docker  

Ideally, here is what a  data app developer need to do to start working,
* Get a `git` client setup on host
* Get data app project code cloned
* Get `atom` setup on host
* Figure out how to edit project 
* Figure out the git commit cycle
* Install `docker` on host
* If not use Jupyter, start `smv` image with project dir mounted
* If use Jupyter, build `smv-jupyter` image, run `smv-jupyter` image with project dir mounted
* In either `smv` or `smv-jupyter` container, user should be able to compile project, run smv through `smv-run`, `smv-shell`, etc. In `smv-jupyter`, the only addition function is to be able to run `smv-jupyter` command
* If using `smv-jupyter` image and with the `smv-jupyter` command running, user should be able to access the Jupyter interface through browser on host

**Comment by guangningyu** [comment]
**In my opinion, what we should provide is just a bash shell.** A docker container should be just a virtual machine with everything installed.
The users should be able to decide what to do in the container. For example, currently the `smv-jupyter` container will automatically start the jupyter notebook and it's not easy to make any changes for the users. It's kind of annoying.

**Comment by guangningyu** [comment]
The `smv` image should be working. I've added the installation of `pip` in the Dockerfile.
I built it on AWS last Friday and it worked.

**Comment by sarahnguvt** [comment]
Agreed that `smv-jupyter` docker should provide users a bash shell with jupyter installed, so that users can compile project, run `smv-jupyter` command and possibly install other packages in python to be used for ad-hoc analyses in jupyter environment.

**Comment by ninjapapa** [comment]
Current `smv` image assumed that there is a "projects" directory on host, where user stored all the `SMV` based projects and also the maven and sbt repositories. When start the docker container, user mount the projects directory to the container, so the maven in docker container will be able to access the repository.

There could be another approach to address the repository issue, that 
* Instead of mount a "projects" directory, mount a single specific "project" directory
* Also user specify a repository (e.g. "~/.m2") to mount to the container 

There are pros and cons on either of them. The "projects" approach will have a shorter docker command line, and user may not need to even aware there is a need of repository on volume. The "project" approach is more explicit and also make it possible to support both bash and command line.

**Comment by guangningyu** [comment]
There's another perspective to think about this question: 

> Should `smv` image cater for user's ad hoc development work only, or should it be used for both development and deployment?

The previous scenario requires more flexibility. `smv` container is just a working environment and the `projects` way is a good choice.

But for the later scenario, the `smv` container is more like a app. For example, a `smv` container may be a dependency of a third party app, where it should be easily created and started via simple commands. For this purpose, mounting only one SMV project under a pre-defined path can make the configuration much easier.

**Comment by guangningyu** [comment]
There're several ways to handle different scenarios:
1. `smv` image only caters for ad hoc development. For deployment, we can create a separate image which is based on `smv` image
2. use `smv` image for both ad hoc development and deployment. We can create multiple options at the entry point. For example, if no commands is given during the container creation, a bash shell is provided by default; if a command `--start-server` is given, start the server after the container is created.

**Comment by AliTajeldin** [comment]
I like that last approach.  A single `smv` image that can be used as a general tools VM and an app runner.  That would require switching to the single project mount (instead of projects).  And instead of mount `.m2` we can just ask for "scratch" space so we can use that for both `.m2` cache and `ivy` cache (sbt).  It also means user doesn't need to know what `.m2` even means.

**Comment by laneb** [comment]
One of the reasons for mounting the .m2 and .ivy2 caches in the first place was that if the user didn't mount the same "scratch space" each time they built a project using the SMV image, the same dependencies would be downloaded each time they built in a new container.

It is intuitive that a self-contained SMV environment would not make tangible changes to the user's host environment (like adding to their mvn or sbt cache), but if the user thinks of the cache mount as an arbitrary "scratch space" for a short-lived container (which it isn't) then probably won't realize that they need to use the same directory every time in order to leverage the cache. We will at minimum need to instruct them to mount the same resource (host directory or data volume) each time.

Perhaps instead of a host directory the cache should be stored on a named volume. Creating one would only add an additional line to the installation instructions (e.g. docker create -v smv_cache).

**Comment by AliTajeldin** [comment]
@laneb : how often would the user need to rerun the `docker create -v smv_cache` command?  Does the volume persist across reboots (i.e. restarts of docker daemon).  And is the operation idempotent (so scripts can just always create the volume and not worry that it already exists). If both of these are true then using a named volume seems to be the best approach.

**Comment by ninjapapa** [comment]
Since we have Jupyter as part of the smv docker image now. This should not be a problem. Also with the user doc updated (3d5c814014674e7213a418ab164c781f1fbfae00), this issue is resolved.
