### ISSUE TITLE
SmvDataSet needs a name method

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#458]

**Comment by Kai-Chen** [comment]
The original `name` method has been renamed to `fqn`, because we use it to locate the module that corresponds to that fqn.  There is also now a `urn` method which is the universal name of the module across implementing language.  The original `name` method was dropped because it is ambiguous in the new module name concept.

That's the rationale for the change :) Is there any practical concern to address by bringing back the `name` method?

**Comment by Kai-Chen** [comment]
Closing as the issue is resolved.
