### ISSUE TITLE
Run smv-jupyter on server need jupyter notebook config

### ISSUE THREAD

**Issue by ShaoyingZhang** [TresAmigosSD/SMV#462]
@guangningyu 

Running jupyter on sever with command: smv-jupyter does not work. Cannot find jupyter notebook config. 

Related to the commit: https://github.com/TresAmigosSD/SMV/commit/76687a5b9933b5b1d4decc4b8669de6b7e512087

**Comment by guangningyu** [comment]
@ShaoyingZhang 
Which Docker image did you use? Please use `tresamigos/smv` and the Jupyter config should be under `/home/smv/.jupyter`.

**Comment by ninjapapa** [comment]
Not everyone is using docker to start smv yet. Also within client server environment, docker engine may not available. Because of that I think we should make "smv-jupyter" script more "intelligent" as below:

* Check whether the "~/.jupyter" exist, if not create it with default parameters 
* Start notebook

**Comment by ninjapapa** [comment]
done.
