### ISSUE TITLE
SMV getting started guide uses scala's smv-run instead of python's

### ISSUE THREAD

**Issue by Khorkhe** [TresAmigosSD/SMV#465]
the SMV getting started guide recommends running a new project created via smv-init, with smv-run --run-app.  It seems the command to be used is smv-pyrun --run-app instead, as the first one fails to execute.

Should the tutorial docs be updated with the correct command? Or will smv-pyrun be eventually renamed to smv-run, hence requiring to revert the docs?

**Comment by AliTajeldin** [comment]
TBD until the unification work is complete.  Since we will always still support smv-shell (the scala version) we may consider having a single `smv-run` (which is the current smv-pyrun) and have a single `smv-shell` with perhaps a `-s` option to indicate a scala shell  as that one would be the odd shell out.

**Comment by laneb** [comment]
Reference to `smv-run` in tutorials have been replaced with `smv-pyrun`. We can switch them back if and when we deprecate `smv-run`.
