### ISSUE TITLE
Still issues in SmvPyModule's hash calculation

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#498]
It sounds now which changing the code obviously, the hash still doesn't change.

**Comment by AliTajeldin** [comment]
The issues appears to be with the use of compiled byte code in the hash computation.  The problem is that with python byte code, it doesn't change for changes in constant values.  For example, the byte code for "a = 6" and "a = 5" are exactly the same.  Constants and strings are interned and their index is used in the byte code.  The short term fix is to use the class code directly (which means the hash will also change if we change the comment inside the class).  We can later remove the comments in a preprocess step.

**Comment by AliTajeldin** [comment]
fixed
