### ISSUE TITLE
smv-init command does not create pom.xml or build.sbt

### ISSUE THREAD

**Issue by cloudysail** [TresAmigosSD/SMV#500]
The `smv-init` command in Master dev branch is different from the one in Docker:
1. It does not create pom.xml or build.sbt. Then how can we build it?
2. Its example usage is `smv-init MyProject` while the one is docker is `smv-init MyProject com.mycompany.myproj`. Which one is correct?

**Comment by AliTajeldin** [comment]
Sorry for the confusion.  SMV is undergoing a major overhaul right now as part of the concentration on python instead of scala as the language of choice.  Some (most?) of the documentation is a bit stale and has not kept up with the changes.
Going forward, the single argument `smv-init` is the one to use.  `smv-init` also takes an argument to determine if you are creating a simple (for tutorial), enterprise (good starting point for a real project), or test example (only used for integration test).

@Khorkhe : please update the documentation to reflect the new changes in `smv-init`

**Comment by AliTajeldin** [comment]
It also appears that the docker version was lagging behind due to build errors in the last couple of days.  It should be fixed shortly and the docker/non-docker versions should be back in sync.

**Comment by laneb** [comment]
The reason why there's no pom.xml or build.sbt is that it is not necessary to build the sample project or any Python-only SMV application.

**Comment by laneb** [comment]
The Docker build is up to date again.

**Comment by cloudysail** [comment]
So I guess I have to download the latest SMV images from docker hub. May need to add "how to update" section about updating to latest SMV using docker in document.

Also, can we version our docker image? In my local docker images, I can see the one I downloaded yesterday(which is not the latest now), but I don't know which version it is. I think it would be helpful if clients can report issues with affects Version information. Right now I can only refer to the 'CREATED' compare to https://hub.docker.com/r/tresamigos/smv/builds/
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
tresamigos/smv      latest              c8504f2c6c1d        2 days ago          1.5 GB

**Comment by AliTajeldin** [comment]
@cloudysail once the major refactor is complete and given a bit of soak time, we will create a docker/non-docker official release of SMV in the 1.5.x series.

**Comment by Khorkhe** [comment]
fixed
