### ISSUE TITLE
Add environment cleanup parameter in smv-pyrun

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#506]
Recently we have a user @fanqingbo who is testing SMV on centOS linux virtual box, and met some issue with `smv-pyrun` under the latest SMV. Specifically, after initializing a project with `smv-init` and directly trying to run `smv-pyrun -m stage1.employment.EmploymentByState` in the command line,  there was no output generated, and the log is as below. 
![default](https://cloud.githubusercontent.com/assets/19701233/23348693/87e9b64c-fce7-11e6-92d1-5bce50ff3f12.jpeg)

However, when trying to run the module in `smv-pyshell` or `smv-jupyter`, the output can be successfully generated with no error.

I am not able to reproduce the issue - After consulting @ninjapapa, it looks like the user's environment setup might have some env parameters which spark-submit picked up and triggered something before smv-pyrun started. On the other hand, `smv-pyshell`/`smv-jupyter` used `pyspark` as the entry point where `pyspark` would internally cleaned up some environment variables and set up some for its own and then triggered `spark-submit`. This might be one possible explanation to this situation where smv-pyrun was not successfully run but smv-pyshell/smv-jupyter worked well.

Given that different users may have various environments to run smv, could we maybe have a parameter in smv-pyrun to force an environment cleanup?

**Comment by AliTajeldin** [comment]
@sarahnguvt : Not sure this is due to environment variables rather than version of python.  Or more likely they have some python init scripts setup that are causing the error as it looks like it is using the ipython kernel when running normal python code.
Please have the user do the following:
* run `env` command and attach the output.
* run `python --version` and attach output.
* run `python` interpreter and see if any errors occur (this is just running plain vanilla `python`, not python inside a notebook)
* if a normal python script works as above (not smv or spark), then see if any of the solutions described here (http://stackoverflow.com/questions/33571421/ipython-notebook-shimwarning-the-ipython-kernel-package-has-been-deprecated) can help.

**Comment by AliTajeldin** [comment]
@sarahnguvt : any feedback from the user with respect to the above request?

**Comment by sarahnguvt** [comment]
@AliTajeldin: the user is also testing on other environments and I will further follow up.

**Comment by sarahnguvt** [comment]
close this issue for now as after upgrading to latest SMV today, the user can now successfully use smv-pyshell/smv-pyrun/smv-jupyter.
