### ISSUE TITLE
`smv-pyrun --help` takes too long to display its options

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#510]
It looks like it first spins up a spark context before just dumping its command line options. Would be great to have it just spit out its options without delay.

**Comment by laneb** [comment]
--help currently incurs a spark-submit because SMV options are parsed in SmvApp using scallop. To work around this would probably require parsing --help in the startup scripts and duplicating the enumeration of options.

**Comment by laneb** [comment]
Actually, instead of caching the message we can use `spark-submit` to run `SmvApp` and print the help message. The big slowdown is the creation of the `SparkContext`, which doesn't happen until after `SmvApp` parses the args. It's slow only for the Python entrypoints because they create a `SparkContext` before the Scala `SmvApp` is created. We have not control over this because `smv-pyshell` runs `pyspark`, which creates the `SparkContext` itself. However, we don't need `pyspark` just to print the help message. `spark-submit` is much faster.

**Comment by laneb** [comment]
Done.
