### ISSUE TITLE
SMV Tutorial Publish to Hive Table Failure

### ISSUE THREAD

**Issue by dxdeidara** [TresAmigosSD/SMV#519]
I was going through the smv docker tutorial. Every step is perfect before Publish to Hive Table. When I've modify the file according to tutorial and run the script, I got the following error messages.
Errors occurred in section: Publish to Hive Table
Link: https://github.com/TresAmigosSD/SMV 
Command ran: smv-pyrun --publish-hive -m stage1.employment.EmploymentByState

20:03:55 PERSISTING: file:///projects/MyApp/data/output/stage1.employment.EmploymentByState_083d2ed2.csv
20:04:02 RunTime: 6 seconds and 609 milliseconds, N: 32
Traceback (most recent call last):
  File "/usr/lib/SMV/tools/../python/smvapp.py", line 33, in <module>
    smvPy.j_smvApp.run()
  File "/usr/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 40, in deco
pyspark.sql.utils.AnalysisException: missing EOF at '.' near 'table'; line 1 pos 29

**Comment by laneb** [comment]
The problem was that the name "my.table.name" was not a valid hive table name. This section of the quickstart is fixed. However, we should also considering moving the section on publishing Hive tables out of the quickstart, as it is not really a basic use case and may overcomplicate things for new users.
