### ISSUE TITLE
Add hashOfHash integration test

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#527]
Depends on #521.

For the following case:
```
F <- M
H <- M
```
where F is a `SmvPyFile`, H is a `SmvPyHiveTable`, and M is a `SmvPyModule`,
need to have the following tests:
* Slight change in F, M's hashOfHash should change
* Slight change in H, M's hashOfHash should change
* Slight change in the data of F, M's hashOfHash should change

**Comment by laneb** [comment]
The data of F _doesn't_ affect its or its descendants' `hashOfHash`, although there are some criteria such as the timestamp on the file which do. There is a test in the integration test which changes the _schema_ for a CSV file and checks that the hash changes. Will that suffice?

If we need specific cases for the first 2 I think the Python unit tests will be a better home -
 integration test cases are slow due to creation of new Spark context.

**Comment by ninjapapa** [comment]
Agreed that the first 2 should be part of the unit tests. 
For the 3rd one, the timestamp logic is a proxy to "data changes". Both data changes and schema changes should be tested.

**Comment by laneb** [comment]
(I gave that last commit got the wrong issue number >_>)

**Comment by laneb** [comment]
Done.

**Comment by laneb** [comment]
Whoops, forgot to make the PR

**Comment by laneb** [comment]
Done.
