### ISSUE TITLE
df in pyshell should be able to infer full SmvDataSet name from the base name

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#543]
When working in pyshell/jupyter, a lot time is actually spend on copy-past the project prefix for the module names. The df command should be able to infer the full name the same way as the -m command line parameter.

**Comment by laneb** [comment]
The cost here is that inferring the name requires discovering all the datasets in a project, which currently can take a significant amount on larger projects. When I previously discussed this with @AliTajeldin, our conclusion was that we should first load the dataset assuming the user has supplied the FQN, and only incur the cost of inferring the name if we determine that the name is not an FQN. We should also make sure that instead of loading all the datasets in the project, we discover only the URNs, then load the dataset(s) by name individually.

**Comment by laneb** [comment]
We decided to skip the step of trying to load the dataset by FQN for 2 reasons:
1) It wouldn't lead to much performance improvement
2) It would lead to somewhat disjointed behavior, because in most contexts SmvApp can only find SmvDataSets that belong to a stage, but if we try to load an FQN directly through the DataSetMgr as described we will also find SmvDataSets which do not belong to a stage.

df() now infers the SmvDataSet given a partial name as long as the SmvDataSet belongs to a stage and there is not a second SmvDataSet with that partial name.
