### ISSUE TITLE
add a isPersisted/needsToRun method to SmvModules

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#560]
This is needed by both the `smv-server` and #559 

Another option is to call this method `needsToRun` which would then filter out inputs and ephemeral modules.

**Comment by laneb** [comment]
It should be sufficient to check if the `moduleCsvPath` is in the output directory, and perhaps if the _SUCCESS file was written.

**Comment by laneb** [comment]
It seems intuitive that ephemeral modules would actually have `needToRun = true` by default, because they do need to run. I would think `needsToRun = isEphemeral || !isPersisted`.

**Comment by laneb** [comment]
It may be useful to note that in solving #554 we concluded that a module is successfully persisted if its schema was written (because the schema is written after the csv.

**Comment by Kai-Chen** [comment]
Per discussion with Ali, both input and ephemeral modules will always return `false` for this method.

The reason why this is preferred to them returning true (some input modules, especially those with dqm and run methods, can also result in persistence of calculated datasets) is that this method will be used in visualization in `smv-server` to see the modules that would be run (usually as the result of a code change)

The alternative specification can be confusing to the user.
In that scenario, given that module `A` depends on an ephemeral module `B`, when user modifies code in module `A`, he will see on the UI that module `B`, though untouched, will also be highlighted as a module that `needs to be run`.
Even though this is in fact exactly what will happen, it is not immediately sensible, especially to one who is not familiar with SMV internals.

For the above reason, this method will return `true` if and only if at least one of the following is true:
- the module has never been run (it has no persisted result set)
- the module has been run, but the code has changed since the previous run

**Comment by AliTajeldin** [comment]
* for ephemeral modules, method should return true if any of its upstream modules return true.
* for input modules, these should be treated as regular modules (they are normally ephemeral).

**Comment by Kai-Chen** [comment]
Feature complete with the above commit.

**Comment by jacobdr** [comment]
Can this be accessed from the Python side yet? I think the answer is no, but wanted to double-check

**Comment by AliTajeldin** [comment]
With the current design, the python side `SmvModule` are considered purely declarative.  Their sole purpose is to just define what should be run and what it depends on.  So we only create a proxy from scala to python but not the other way around.  The python side module can not access the state of the smv module without some major hacking.
Once we move the core of SMV into python in the future, the above would be possible.

If we just want to find out what is runnable in the app, we can get the json graph (soon to be renamed module discovery or something similar).
