### ISSUE TITLE
Refactor SmvApp and SmvPy

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#586]
A significant part of the responsibility of `SmvApp` is just to delegate to `SmvPy`. The two should be merged. `SmvPy` will be renamed to `SmvApp` and take over adding user source to the sys.path and also as the entrypoint to run applications.

**Comment by jacobdr** [comment]
We had a use case in our project for running an arbitrary Python script in a context in which `smvPy` singleton was already initialized, so that we should import/reference it and do things like `runModuleByName`. 

Creating a custom shell wrapper to run `_env.sh` and `pyenv.sh` was fine, but things got hairy when that wrapper had to then call a Python script to start the SMV app, and then that "App Starter" script used `execfile` to finally call the script the user wanted. Phew.

Maybe out of scope for this ticket, but would be great if in this refactor you bore such a use case in mind.

**Comment by laneb** [comment]
The difference following this refactor will be that 

- `SmvPy` is renamed to `SmvApp`
- `SmvApp` adds user source to the `sys.path`
- `SmvApp` provides a method `run` that delegates to its j_smvApp to run the application
- `SmvApp` singleton is not imported directly. It is accessed via `SmvApp.getInstance`
- `SmvApp` singleton is not created automatically. It should be created by SMV entrypoints using `SmvApp.createInstance`.

**Comment by laneb** [comment]
@jacobdr I don't quite follow. Is there something in particular you wanted to see out of this refactor?
