### ISSUE TITLE
Smv Pyshell/Jupyter nameSpace error cause df nonfunction

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#589]
For  Pyshell/Jupyter, the expected behavior is that
* df(module) should work as long as the module in the command and its upstream modules can be resolved, any other module even if there are syntax errors should not impact

There is a case that anywhere in the project, if a line of code imports a module from a stage that is non-exist. For example:
`from stage import data`
but stage folder does not exist, then df(module) does not function, although calling df would produce the right error message pointing to the source of issue. 

Is this expected behavior or do we want to make SMV more resilient to this type of issue when developing using python interface?

**Comment by laneb** [comment]
This is by design, though there may be a better design. The reason for this behavior is:

 The Python `df` delegates to the Scala `SmvApp.runModuleByName`, which tries to guess the full name of the `SmvModule` you are indicating (so that e.g. you can do `df("mod")` instead of `df("app.stage.mod")`). In order to accomplish this, we load the names of all the modules in the project, which requires us to import every subpackage of every stage and look inside for objects that are `SmvDataSets`, collect all of their FQNs, then find the unique FQN that ends with the given name. If there is a syntax error in a package in the project, the`SmvModules` inside will not be imported and Python will raise an error. In order for SMV to be 'resilient' in this situation, we have to suppress the error, but this would mean silently ignoring all of the `SmvModules` in the broken package as though they weren't there.

E.g. 
Given a module with a syntax error
```
# In the package stage1.modules
class MyMod(SmvModule):
    # missing a colon
    def requiresDS()  return [] 
```
when you ran
```
df("MyMod")
```
you would get a "Cannot find module" error.

**Comment by laneb** [comment]
Perhaps a better approach than throwing an error would be to issue a warning about each package that has syntax errors.

**Comment by XiaosenChen** [comment]
@laneb Thanks Lane, this makes great sense. I agree,the cost of suppressing this error outweighs the error itself. I think warning message is great, only now I wonder whether SMV should be more resilient in such situation. For example, we want to tolerate the syntax error inside a module during active development, but do we really want to tolerate syntax error in package namespace? I need to think more on this...

**Comment by ninjapapa** [comment]
The behavior changes here since we introduce the name inferring mechanism. Catching syntax error at the first place should be a good thing, even in active development phase, as long as the message is clear enough to help user to pinpoint the syntax error. 

The following 2 places are common for this to happen, assume `M1` has a syntax error,
* `df(M2)` where M2 has no relationship to M1 at all,
* `ls()`

The error message enhancement for those 2 could be the same place in the code.

**Comment by laneb** [comment]
What would make the error clearer? We currently print the trace for the syntax error, including the file, line, and location on the line of the error.

**Comment by XiaosenChen** [comment]
message is quite comprehensive, maybe user need some sort of hint still? @Khorkhe @ktlu4 may be able to weigh in on this, since they had experienced this issue recently.

**Comment by ninjapapa** [comment]
My bad. From the description from the email chain I got the impression that we are not printing the trace. Since we are already printing, and there are no easy way for us to control the error message at this point. I suggest to close this issue.

**Comment by jacobdr** [comment]
I like the current behavior. Fail fast, fix fast.

Also, on the Python side, when an exception is thrown while loading a
module, it never makes it to the Dasaset cache. So a user can go in and
modify the source code, and then df(module) again, and will properly --
without even having to exit the shell.

**Comment by AliTajeldin** [comment]
@jacobdr 👍 
I agree.  I like the fail fast approach.  Just like in scala, we would not have been able to compile the code if there was a syntax error anywhere.

**Comment by XiaosenChen** [comment]
@AliTajeldin
closing. I have a related question: as user switching from Scala Interface, what type of errors that prevent Scala project from compiling will I expect NOT to see as 'fail fast' when resolving a module with Python, and vice versa?For example, I won't see type mismatch?

**Comment by laneb** [comment]
You will not see type errors. It would be difficult to enumerate all of the things that Scala will catch at compile time that Python SMV won't fail fast for. Python SMV _will_ fail fast for :

- all syntax errors, like my example
- (basically) all import errors, like `import smb` instead of `import smv`
- _some_ name errors, like `class M1 extends(SmbModule):` instead of `class M1 extends(SmvModule):`

but not a lot else that you would run into in practice.

**Comment by laneb** [comment]
As a general rule, don't expect errors inside of method definitions (besides syntax errors) to fail fast. These kinds of errors will generally be caught at runtime.
