### ISSUE TITLE
graph command in Jupyter should show the SVG from the dot graph

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#611]
Currently `guru.nidi.graphviz` package is configured on the Scala side to convert the dot graph to png. Since creating the png or whatever plot files is only for Jupyter, it's more natural to let Scala/Java side to deliver the dot string, and let Python side to handle how to display the dot. 

Python package `graphviz` is just for it. "Input[2]" of this example shows how we can do it:
https://github.com/xflr6/graphviz/blob/master/examples/notebook.ipynb

As long as `graphviz` is installed, we can already do the following in an smv-jupyter,
```python
j=SmvApp.getInstance().j_smvApp
g=j.dependencyGraphDotString(j.stages())
from graphviz import Source
Source(g)
```

**Comment by Kai-Chen** [comment]
The `graph()' method in `smvshell.py` produces the textual graph using the `ascii-graphs` library.

This is necessary because the `__repr__` method in Python can only return an ascii (8-bit) string, whereas the graph produced by `ascii-graphs` uses unicode for prettier rectangle corners, and cannot be returned from the `__repr__` method and must be printed as a side effect.
That, however, does not look nice in Jupyter Notebook, as the jumbled text is produced a long with the nice SVG graph.

**Comment by ninjapapa** [comment]
done.
