### ISSUE TITLE
moving project .py file without deleting .pyc caused 2 modules being found under the name

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#612]
-dir1
--location.py (contain module M definition)
--location.pyc
-dir2

After moving file
-dir1
--location.pyc
-dir2
--location.py

after moving the file, when df("M"), error message suggest that I have two places with "M": dir1.location.M, dir2.location.M. Is there a better way then for the user remember to always delete .pyc in the previous dir?

**Comment by ninjapapa** [comment]
We can do a clean up (removing .pyc files) when start smv-pyshell. But without restarting the shell, user still need to clean up themselves.

**Comment by AliTajeldin** [comment]
The same issue will occur with `smv-pyrun` when we infer the name of the module.  May need to move the delete of `*.pyc` into the `._pyenv.sh` file.  But we should also consider the time it will retake to recompile everything.  A quick timing test may be needed.
TBD: determine if there is a way in python to suppress the creation of the pyc files in the first place.

**Comment by laneb** [comment]
Another option may be to delete the `.pyc` files in `DataSetRepo._moduleUrnsForStage`. I guess it is possible that this would be prohibitively slow, but if not then the user wouldn't have to do the cleanup themselves even while in the shell.

**Comment by laneb** [comment]
Also, by my reading this issue is slightly different from what was described in #596. That issue was about Python not recompiling code for which `.pyc` files already exist (but may be outdated), while this is about Python using leftover `.pyc` files compiled from source that has been deleted.

**Comment by laneb** [comment]
For Cython >= 2.6, there is a command line option, an environment variable, and a `sys` attribute, each of which will suppress creation of `.pyc` files. Don't know if it affects behavior or performance.

**Comment by laneb** [comment]
Suppressing `.pyc` files is generally expected to increase time spent importing modules, so I am benchmarking a 1000 module SMV app with and without the  `.pyc` files. For module discovery  , Suppressing `.pyc` files actually speeds up discovery of modules (using `ls()`) in shell) by >10%, but only the first time. What I mean is that the first time you use `ls()` in a single `smv-pyshell`,
- without `.pyc` files took about 6.7s 
- with `.pyc` files took about 5.4s 
while the second time 
- without `.pyc` files took about 4.6s 
- with `.pyc` files took about 5.4s 
BUT after restarting the shell you go back to first timing. This makes sense because we incur IO cost the first time, leverage the cache the second time, and have to recompile the code after restarting Python. I expect that loading modules will be consistently faster without `.pyc` files, since we force recompilation of modules already.

**Comment by laneb** [comment]
We suppressed `.pyc` files as part of the solution to #646. You can now move your `.py` files around without causing problems.
