### ISSUE TITLE
Need an option to add jars to the classpath

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#627]
If you use Spark's `--jars` it is ignored, probably because it's the second --jars option in the resulting `spark-submit` (first one is for the `APP_JAR`). Listing additional jars with the `APP_JAR` works.

**Comment by laneb** [comment]
@AliTajeldin Thoughts on just adding an `--smv-jars` option that's included in the `--jars` for the `spark-submit`?

**Comment by AliTajeldin** [comment]
So I guess we have two options:
* add `--smv-jars` options and we append those to the generated `--jars` that we pass to `spark-submit` (int addition to the `APP_JAR`)
* parse the spark `--jars` options being passed to `smv-pyrun` and build a new `--jars` that includes the `APP_JAR`

The first option is easier to implement but requires additional documentation.  The second option is harder to implement but is more natural for the user (that is what they would expect).  Since users generally don't read the documentation and will probably expect to be able to supply their own `--jars` option to `smv-pyrun` as part of the spark options, I think we should do option 2 unless it is extremely difficult (shouldn't be).

**Comment by laneb** [comment]
Makes sense.

**Comment by laneb** [comment]
Done.
