### ISSUE TITLE
Replace custom CSVParser with scala-csv

### ISSUE THREAD

**Issue by hubertp-lshift** [TresAmigosSD/SMV#637]
https://github.com/tototoshi/scala-csv supports everything that we use CSVParser for and is still maintained.

**Comment by AliTajeldin** [comment]
I think @ninjapapa did some timing tests at some point and found that the current csv module was much faster.  This is from a couple of years ago and I don't know if the speedup still holds or if he tested with scala-csv.

**Comment by ninjapapa** [comment]
scala-csv has very big performance issue (order of magnitude slower). Since CSV parsing is very critical to SMV, we need to be very carful on changes. 
We should rather consider to 
* Using Spark supported format for intermediate data persisting, and then
* Adopt Spark's CSV handling to read in CSV files

Both of them should already have issues. Given the fact that this issue is very critical to SMV, there are no strong reason to make the change yet. I should rather close this issue.

**Comment by AliTajeldin** [comment]
Closing as will not fix.
