### ISSUE TITLE
smvExportCsv doesn't work on real cluster environment 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#764]
In real cluster environment, executor many not have the local directory mounted. Since latest `smvExportCsv` uses iterator on RDD to access each row and call Java io to write, the Java IO run on a single executor instead of run on the master, so that can't access master machine's local file system.

**Comment by laneb** [comment]
We might be able to collect and reduce the RDD to a string and then save the string. I'm not certain this would work, though, because when we use this approach elsewhere the string has no newlines.

**Comment by AliTajeldin** [comment]
using collect has two issues:
* will try to read entire DF result into memory (which is why we modified the code)
* still will not work with yarn-cluster mode as the driver will be running on a node instead of the gateway machine.

Ideally, we should find a way to collect a partition at a time on the driver side.  It would address the first issue above but not the second (not a common use-case).

**Comment by ninjapapa** [comment]
We can write to hdfs first, and then use `copyToLocalFile` method of `org.apache.hadoop.fs.FileSystem` to copy them out to local. In that way the "copy" operation is on the driver machine only.

**Comment by jacobdr** [comment]
Saw an issue yesterday with a Java heap OOM error while using this method.
Had to bump the goose the driver memory fairly high to get around it -- I
am hoping that this ticket might also cover that case.


On May 17, 2017, 07:35 +1000, Bo Zhang <notifications@github.com>, wrote:

We can write to hdfs first, and then use copyToLocalFile method of
org.apache.hadoop.fs.FileSystem to copy them out to local. In that way the
"copy" operation is on the driver machine only.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TresAmigosSD/SMV/issues/764#issuecomment-301922888>,
or mute
the thread

**Comment by AliTajeldin** [comment]
@jacobdr which method are you referring to in "Saw an issue yesterday with a Java heap OOM error while using this method"?  The old collect all or the `copyToLocalFile` method?

**Comment by jacobdr** [comment]
I suppose the former -- we are still on version 1.5.2.6, so whatever was
implemented at that time

**Comment by AliTajeldin** [comment]
ok, good.  I was worried our new method is already fraught with OOM issues.

**Comment by ninjapapa** [comment]
PR #779
