### ISSUE TITLE
SmvApp need a verify method

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#84]
SmvModule should have a "verify" method which get override by the concrete object method. A command line parameter for running an App should allow not only generate the module data file, but run the verify method.

**Comment by ninjapapa** [comment]
We will persist the QA edd for each persisted module as long as the command line parameter specified. Then the verify method could be edd SchemaRdd instead of the module data themselves.

**Comment by AliTajeldin** [comment]
My guess is we would need all three as parameters (original input srdd, actual output srdd, and edd srdd).  99.9% of the time, the verify will be just a check against the edd but we never know if the user needs to perform some operation on the output that is not available in edd and we dont want edd to be the union of all possible things we want to check (might be very case specific).

**Comment by ninjapapa** [comment]
Sounds like 2 deferent levels of requirements to me. One is more generic and the other is specifically check the predefined statistics of the data, which cover 99% of the cases of covering the bottom. The DQM function may also belong to the generic verify method.

**Comment by AliTajeldin** [comment]
I guess it all comes down to what we are testing/validating.  To test the "code", we need a fixed known input and a validate method that will test for the expected output (which might be statistical based as well).  To test the "data", we probably only care about the statistical output to make sure we didn't accidentally screw something up because either the input changed or the code broke something.

**Comment by ninjapapa** [comment]
implemented in the validation framework
