### ISSUE TITLE
some advice about smv

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#948]
**1)add the function of indicating current step**
if I have a project moduleA depends moduleB while moduleB depends moduleC like below
 moduleC 
    ^
     |
moduleB 
    ^
     |
moduleA 

when I execute moduleA(forceRun=True), the execution order is moduleC first,moduleB second,moduleA last.
but when I execute moduleA(forceRun=False),maybe not the above execution order

I think SMV likes bigdata workflow(maybe cdh oozie),is there any function to indicating current step(I want to know the current status of executation and which step is ignored)?

**2)support parameter in df function**
now def df(name, forceRun = False, version = None):
I think it is better to def df(name, forceRun = False, params={}, version = None) or insert **kwargs

because we should run the module on different time windows, I do not want to hard code in module

**Comment by laneb** [comment]
1.

2. Is it that you want the module's `run` method to accept additional arguments which would be passed through `df`? This would be problematic because there would be no way of running the module outside of the shell. Have you considered using the [runtime config](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/run_config.md)?

**Comment by jimmycheng603** [comment]
tks @laneb  it helps

**Comment by jimmycheng603** [comment]
@AliTajeldin 
1. your answer helps
2. laneb's reply has solved my question
