### ISSUE TITLE
.pyc files included in 2.1.1.1 build

### ISSUE THREAD

**Issue by daStrauss** [TresAmigosSD/SMV#954]
In unpacking the latest 2.1.1.1 build, I noticed that the .pyc files from previous versions seem to be included in the final zip build. I recommend that the build process be updated to exclude any of these python artifacts.

**Comment by laneb** [comment]
@AliTajeldin The build script can be updated to omit .pyc files, but I'm surprised that we are creating them in the first place since we added the .pyc suppression a while ago. I notice now that I have them too, but I'm sure i deleted them since that change. After removing them and running `smv-pyrun` they are not regenerated. I wonder if there are circumstances in which we may also generate .pyc files for client applications.

**Comment by AliTajeldin** [comment]
They pyc files were probably on the build machine from way back.  Need to remove them there.

**Comment by Kai-Chen** [comment]
Will also remove any `__pycache__` subdirectory.
