### ISSUE TITLE
how to enable remote debug in idea for smv

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#966]
how to enable remote debug in idea for smv or how to debug smv codes in your development. Do you debug code by unit test or other methods?

**Comment by AliTajeldin** [comment]
SMV (or more accurately Spark) is a bit difficult to debug at runtime.  This is because the code you write only creates a recipe for what needs to be done that Spark then takes and optimizes and distributes to multiple executors.  So debugging the running of the code only debugs the building of the recipe.
One of the reasons we created SMV was to help with the issue of running on distributed systems.  By using SMV, you can break down the problem to solve into small manageable pieces.  We recommend that you write small modules and test them individually (by using jupyter and/or adding DQM rules to the module).

**Comment by jimmycheng603** [comment]
thanks for your detailed answer. but how to debug the smv framework(smv source code)? I want to know smv working principle and detailed  implementation.

**Comment by AliTajeldin** [comment]
Can you provide an example of what you are trying to debug?

**Comment by jimmycheng603** [comment]
if I have modified som scala codes in smv framework(smv source codes),I want to verify if it is ok, how can I debug it like python application or java application, I do not want to assembly the smv to test the modified code for it has consumed too much time.
I have browsed the unittest, maybe I know how to debug it(start spark in local mode), I will try it.

**Comment by jimmycheng603** [comment]
I have found run-integration-test.sh,I think it is used to test the core of smv written by scala, then you assemble smv framework to fat jar, then smv-pytest is used for testing python shell.

**Comment by AliTajeldin** [comment]
You can setup your ide to debug scala code as normal but generally we test SMV code by running it and looking at the resulting data.  Looking at the code as it is running (as is the case in traditional debugging) will only show you the dependency graph creation step.  That is handy if you are developing Spark itself.  For development of SMV and Spark apps in general, the result data is what you need to observe.  So you must pay the price and run the data.  This is also why we prefer python over scala,  you don't have to pay the price of compile.

**Comment by jimmycheng603** [comment]
thanks for your reply
