### ISSUE TITLE
Support more modes to run modules

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#994]
Currently SMV running mode is dependent on code changes. 

Input  -> Module A -> Module B  

In above graph, module B calls module A. If code in A changes and I run module B, module A and module B will both be triggered. 

Running mode based on code changes is useful in most cases but also has some limitations:
1. User only focuses on developing module B and wants to avoid triggering upstream modules.
2. Input data refreshes and users want to trigger module B and all its dependencies.

For limitation1, we can support a running mode that always trigger module itself and ignore the code changes. It is also safer to avoid the code mistakes caused by teammates during code development.

For limitation2, there are two ways to solve it:
1) Trigger module and all its dependencies.
2) Capture the refreshed data, trigger module and its part of dependencies which relate to the refreshed data.

**Comment by ninjapapa** [comment]
For 1. In current SMV, we used the stage-publish concept to "pin" a data to some historical version. We are considering capability to pin a specific module to some historical version from a different requirement. The key is to make user aware which version of data (or the data created by which version of code) he is using, which should be managed, instead of just leave it to user to figure out, which will easily cause confusions quickly.

For 2. In case the input data is CSV, since the hash of SmvCSVFile depends on file's last update time, and file's absolute path, data update will trigger downstream module to rerun. In case the input is a Hive table, user may need to have a mechanism to modify the "version" method of the input module, either manually change the code, or configuration, or triggered by some specific DB table which holds the last update time of the data table. As long as the "version" of the input module changes, all downstream module will re-run.

**Comment by yw-yang** [comment]
Agree with the design stated above. 

For 1, the capability to pin a specific module is necessary especially for a big stage that many users will involve in the development work.

For 2, it works and looks good.

**Comment by AliTajeldin** [comment]
Let's go ahead and close this ticket.  The pinning solution is in another app and will not be done at the SMV level.
